services:
  - type: web
    name: mcplayeralt
    runtime: node
    buildCommand: npm install
    startCommand: npm run deploy && npm start
    healthCheckPath: /health
    envVars:
      - key: TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: NODE_VERSION
        value: "18.17.0"
